/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { PromoResumeInterface, } from "./components/cnt-flexy-view-adam-promo-resume-wrapper/res/view/cnt-flexy-view-adam-promo-resume-wrap/res/interface/iterface.common";
import { PromoFooterBlockInterface, } from "./components/cnt-flexy-view-adam-promo-footer-wrapper/res/view/cnt-flexy-view-adam-promo-footer/res/interface/common.interface";
import { PromoMenuItemsInterface, } from "./components/cnt-flexy-view-adam-promo-header-wrapper/res/view/cnt-flexy-view-adam-promo-header/res/interface/common.interface";
import { PromoIntroBlockInterface, } from "./components/cnt-flexy-view-adam-promo-intro-wrapper/res/view/cnt-flexy-view-adam-promo-intro/res/interface/common.interface";
import { PromoPortfolioInterface, } from "./components/cnt-flexy-view-adam-promo-portfolio-wrapper/res/view/cnt-flexy-view-adam-promo-portfolio/res/interface/common.interface";
export namespace Components {
    interface CntFlexyViewAdamPromoEducation1_01 {
        /**
          * Данные для блока "образование"
         */
        "payload": PromoResumeInterface;
    }
    interface CntFlexyViewAdamPromoEducationBlock {
        /**
          * Данные для блока "образование"
         */
        "payload": any;
    }
    interface CntFlexyViewAdamPromoEmployment1_01 {
        /**
          * Данные для блока "Опыт работы"
         */
        "payload": PromoResumeInterface;
    }
    interface CntFlexyViewAdamPromoEmploymentBlock {
        /**
          * Данные для блока "Опыт работы"
         */
        "payload": any;
    }
    interface CntFlexyViewAdamPromoFooter {
        /**
          * Данные для футера
         */
        "categories": PromoFooterBlockInterface;
    }
    interface CntFlexyViewAdamPromoFooterWrapper1_01 {
        /**
          * Данные для футера
         */
        "categories": PromoFooterBlockInterface;
    }
    interface CntFlexyViewAdamPromoHeader {
        /**
          * Элементы меню
         */
        "categories": PromoMenuItemsInterface[];
    }
    interface CntFlexyViewAdamPromoHeaderMenu {
        /**
          * Ссылки меню
         */
        "menuItems": PromoMenuItemsInterface;
    }
    interface CntFlexyViewAdamPromoHeaderWrapper1_01 {
        /**
          * Элементы меню
         */
        "categories": PromoMenuItemsInterface[];
    }
    interface CntFlexyViewAdamPromoHello {
        /**
          * Описание блока Hello
         */
        "payload": string;
    }
    interface CntFlexyViewAdamPromoHelloWrapper1_01 {
        /**
          * Описание блока Hello
         */
        "payload": string;
    }
    interface CntFlexyViewAdamPromoIntro {
        /**
          * Данные для блока интро
         */
        "payload": PromoIntroBlockInterface;
    }
    interface CntFlexyViewAdamPromoIntroWrapper1_01 {
        /**
          * Данные для блока интро
         */
        "payload": PromoIntroBlockInterface;
    }
    interface CntFlexyViewAdamPromoMobileMenu {
        /**
          * Ссылки меню
         */
        "menuItems": PromoMenuItemsInterface;
    }
    interface CntFlexyViewAdamPromoPortfolio {
        /**
          * Карточки портфолио
         */
        "payload": PromoPortfolioInterface;
    }
    interface CntFlexyViewAdamPromoPortfolioCards {
        /**
          * Карточки портфолио
         */
        "payload": any;
    }
    interface CntFlexyViewAdamPromoPortfolioMenu {
        /**
          * Данные для категорий
         */
        "payload": any;
    }
    interface CntFlexyViewAdamPromoPortfolioStack {
        /**
          * Данные для компонента stack
         */
        "stackList": any;
    }
    interface CntFlexyViewAdamPromoPortfolioWrapper1_01 {
        /**
          * Карточки портфолио
         */
        "payload": PromoPortfolioInterface;
    }
    interface CntFlexyViewAdamPromoResume1_01 {
        /**
          * Текст с описанием блока
         */
        "payload": PromoResumeInterface;
    }
    interface CntFlexyViewAdamPromoResumeWrap {
        /**
          * Текст с описанием блока
         */
        "payload": any;
    }
    interface CntFlexyViewAdamPromoResumeWrapper1_01 {
        /**
          * Текст с описанием блока
         */
        "payload": any;
    }
    interface CntFlexyViewAdamPromoSkills1_01 {
        /**
          * Данные для блока "Мои навыки"
         */
        "payload": PromoResumeInterface;
    }
    interface CntFlexyViewAdamPromoSkillsBlock {
        /**
          * Данные для блока "Мои навыки"
         */
        "payload": any;
    }
    interface MyComponent {
    }
}
declare global {
    interface HTMLCntFlexyViewAdamPromoEducation1_01Element extends Components.CntFlexyViewAdamPromoEducation1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAdamPromoEducation1_01Element: {
        prototype: HTMLCntFlexyViewAdamPromoEducation1_01Element;
        new (): HTMLCntFlexyViewAdamPromoEducation1_01Element;
    };
    interface HTMLCntFlexyViewAdamPromoEducationBlockElement extends Components.CntFlexyViewAdamPromoEducationBlock, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAdamPromoEducationBlockElement: {
        prototype: HTMLCntFlexyViewAdamPromoEducationBlockElement;
        new (): HTMLCntFlexyViewAdamPromoEducationBlockElement;
    };
    interface HTMLCntFlexyViewAdamPromoEmployment1_01Element extends Components.CntFlexyViewAdamPromoEmployment1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAdamPromoEmployment1_01Element: {
        prototype: HTMLCntFlexyViewAdamPromoEmployment1_01Element;
        new (): HTMLCntFlexyViewAdamPromoEmployment1_01Element;
    };
    interface HTMLCntFlexyViewAdamPromoEmploymentBlockElement extends Components.CntFlexyViewAdamPromoEmploymentBlock, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAdamPromoEmploymentBlockElement: {
        prototype: HTMLCntFlexyViewAdamPromoEmploymentBlockElement;
        new (): HTMLCntFlexyViewAdamPromoEmploymentBlockElement;
    };
    interface HTMLCntFlexyViewAdamPromoFooterElement extends Components.CntFlexyViewAdamPromoFooter, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAdamPromoFooterElement: {
        prototype: HTMLCntFlexyViewAdamPromoFooterElement;
        new (): HTMLCntFlexyViewAdamPromoFooterElement;
    };
    interface HTMLCntFlexyViewAdamPromoFooterWrapper1_01Element extends Components.CntFlexyViewAdamPromoFooterWrapper1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAdamPromoFooterWrapper1_01Element: {
        prototype: HTMLCntFlexyViewAdamPromoFooterWrapper1_01Element;
        new (): HTMLCntFlexyViewAdamPromoFooterWrapper1_01Element;
    };
    interface HTMLCntFlexyViewAdamPromoHeaderElement extends Components.CntFlexyViewAdamPromoHeader, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAdamPromoHeaderElement: {
        prototype: HTMLCntFlexyViewAdamPromoHeaderElement;
        new (): HTMLCntFlexyViewAdamPromoHeaderElement;
    };
    interface HTMLCntFlexyViewAdamPromoHeaderMenuElement extends Components.CntFlexyViewAdamPromoHeaderMenu, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAdamPromoHeaderMenuElement: {
        prototype: HTMLCntFlexyViewAdamPromoHeaderMenuElement;
        new (): HTMLCntFlexyViewAdamPromoHeaderMenuElement;
    };
    interface HTMLCntFlexyViewAdamPromoHeaderWrapper1_01Element extends Components.CntFlexyViewAdamPromoHeaderWrapper1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAdamPromoHeaderWrapper1_01Element: {
        prototype: HTMLCntFlexyViewAdamPromoHeaderWrapper1_01Element;
        new (): HTMLCntFlexyViewAdamPromoHeaderWrapper1_01Element;
    };
    interface HTMLCntFlexyViewAdamPromoHelloElement extends Components.CntFlexyViewAdamPromoHello, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAdamPromoHelloElement: {
        prototype: HTMLCntFlexyViewAdamPromoHelloElement;
        new (): HTMLCntFlexyViewAdamPromoHelloElement;
    };
    interface HTMLCntFlexyViewAdamPromoHelloWrapper1_01Element extends Components.CntFlexyViewAdamPromoHelloWrapper1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAdamPromoHelloWrapper1_01Element: {
        prototype: HTMLCntFlexyViewAdamPromoHelloWrapper1_01Element;
        new (): HTMLCntFlexyViewAdamPromoHelloWrapper1_01Element;
    };
    interface HTMLCntFlexyViewAdamPromoIntroElement extends Components.CntFlexyViewAdamPromoIntro, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAdamPromoIntroElement: {
        prototype: HTMLCntFlexyViewAdamPromoIntroElement;
        new (): HTMLCntFlexyViewAdamPromoIntroElement;
    };
    interface HTMLCntFlexyViewAdamPromoIntroWrapper1_01Element extends Components.CntFlexyViewAdamPromoIntroWrapper1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAdamPromoIntroWrapper1_01Element: {
        prototype: HTMLCntFlexyViewAdamPromoIntroWrapper1_01Element;
        new (): HTMLCntFlexyViewAdamPromoIntroWrapper1_01Element;
    };
    interface HTMLCntFlexyViewAdamPromoMobileMenuElement extends Components.CntFlexyViewAdamPromoMobileMenu, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAdamPromoMobileMenuElement: {
        prototype: HTMLCntFlexyViewAdamPromoMobileMenuElement;
        new (): HTMLCntFlexyViewAdamPromoMobileMenuElement;
    };
    interface HTMLCntFlexyViewAdamPromoPortfolioElement extends Components.CntFlexyViewAdamPromoPortfolio, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAdamPromoPortfolioElement: {
        prototype: HTMLCntFlexyViewAdamPromoPortfolioElement;
        new (): HTMLCntFlexyViewAdamPromoPortfolioElement;
    };
    interface HTMLCntFlexyViewAdamPromoPortfolioCardsElement extends Components.CntFlexyViewAdamPromoPortfolioCards, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAdamPromoPortfolioCardsElement: {
        prototype: HTMLCntFlexyViewAdamPromoPortfolioCardsElement;
        new (): HTMLCntFlexyViewAdamPromoPortfolioCardsElement;
    };
    interface HTMLCntFlexyViewAdamPromoPortfolioMenuElement extends Components.CntFlexyViewAdamPromoPortfolioMenu, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAdamPromoPortfolioMenuElement: {
        prototype: HTMLCntFlexyViewAdamPromoPortfolioMenuElement;
        new (): HTMLCntFlexyViewAdamPromoPortfolioMenuElement;
    };
    interface HTMLCntFlexyViewAdamPromoPortfolioStackElement extends Components.CntFlexyViewAdamPromoPortfolioStack, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAdamPromoPortfolioStackElement: {
        prototype: HTMLCntFlexyViewAdamPromoPortfolioStackElement;
        new (): HTMLCntFlexyViewAdamPromoPortfolioStackElement;
    };
    interface HTMLCntFlexyViewAdamPromoPortfolioWrapper1_01Element extends Components.CntFlexyViewAdamPromoPortfolioWrapper1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAdamPromoPortfolioWrapper1_01Element: {
        prototype: HTMLCntFlexyViewAdamPromoPortfolioWrapper1_01Element;
        new (): HTMLCntFlexyViewAdamPromoPortfolioWrapper1_01Element;
    };
    interface HTMLCntFlexyViewAdamPromoResume1_01Element extends Components.CntFlexyViewAdamPromoResume1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAdamPromoResume1_01Element: {
        prototype: HTMLCntFlexyViewAdamPromoResume1_01Element;
        new (): HTMLCntFlexyViewAdamPromoResume1_01Element;
    };
    interface HTMLCntFlexyViewAdamPromoResumeWrapElement extends Components.CntFlexyViewAdamPromoResumeWrap, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAdamPromoResumeWrapElement: {
        prototype: HTMLCntFlexyViewAdamPromoResumeWrapElement;
        new (): HTMLCntFlexyViewAdamPromoResumeWrapElement;
    };
    interface HTMLCntFlexyViewAdamPromoResumeWrapper1_01Element extends Components.CntFlexyViewAdamPromoResumeWrapper1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAdamPromoResumeWrapper1_01Element: {
        prototype: HTMLCntFlexyViewAdamPromoResumeWrapper1_01Element;
        new (): HTMLCntFlexyViewAdamPromoResumeWrapper1_01Element;
    };
    interface HTMLCntFlexyViewAdamPromoSkills1_01Element extends Components.CntFlexyViewAdamPromoSkills1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAdamPromoSkills1_01Element: {
        prototype: HTMLCntFlexyViewAdamPromoSkills1_01Element;
        new (): HTMLCntFlexyViewAdamPromoSkills1_01Element;
    };
    interface HTMLCntFlexyViewAdamPromoSkillsBlockElement extends Components.CntFlexyViewAdamPromoSkillsBlock, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAdamPromoSkillsBlockElement: {
        prototype: HTMLCntFlexyViewAdamPromoSkillsBlockElement;
        new (): HTMLCntFlexyViewAdamPromoSkillsBlockElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "cnt-flexy-view-adam-promo-education-1_01": HTMLCntFlexyViewAdamPromoEducation1_01Element;
        "cnt-flexy-view-adam-promo-education-block": HTMLCntFlexyViewAdamPromoEducationBlockElement;
        "cnt-flexy-view-adam-promo-employment-1_01": HTMLCntFlexyViewAdamPromoEmployment1_01Element;
        "cnt-flexy-view-adam-promo-employment-block": HTMLCntFlexyViewAdamPromoEmploymentBlockElement;
        "cnt-flexy-view-adam-promo-footer": HTMLCntFlexyViewAdamPromoFooterElement;
        "cnt-flexy-view-adam-promo-footer-wrapper-1_01": HTMLCntFlexyViewAdamPromoFooterWrapper1_01Element;
        "cnt-flexy-view-adam-promo-header": HTMLCntFlexyViewAdamPromoHeaderElement;
        "cnt-flexy-view-adam-promo-header-menu": HTMLCntFlexyViewAdamPromoHeaderMenuElement;
        "cnt-flexy-view-adam-promo-header-wrapper-1_01": HTMLCntFlexyViewAdamPromoHeaderWrapper1_01Element;
        "cnt-flexy-view-adam-promo-hello": HTMLCntFlexyViewAdamPromoHelloElement;
        "cnt-flexy-view-adam-promo-hello-wrapper-1_01": HTMLCntFlexyViewAdamPromoHelloWrapper1_01Element;
        "cnt-flexy-view-adam-promo-intro": HTMLCntFlexyViewAdamPromoIntroElement;
        "cnt-flexy-view-adam-promo-intro-wrapper-1_01": HTMLCntFlexyViewAdamPromoIntroWrapper1_01Element;
        "cnt-flexy-view-adam-promo-mobile-menu": HTMLCntFlexyViewAdamPromoMobileMenuElement;
        "cnt-flexy-view-adam-promo-portfolio": HTMLCntFlexyViewAdamPromoPortfolioElement;
        "cnt-flexy-view-adam-promo-portfolio-cards": HTMLCntFlexyViewAdamPromoPortfolioCardsElement;
        "cnt-flexy-view-adam-promo-portfolio-menu": HTMLCntFlexyViewAdamPromoPortfolioMenuElement;
        "cnt-flexy-view-adam-promo-portfolio-stack": HTMLCntFlexyViewAdamPromoPortfolioStackElement;
        "cnt-flexy-view-adam-promo-portfolio-wrapper-1_01": HTMLCntFlexyViewAdamPromoPortfolioWrapper1_01Element;
        "cnt-flexy-view-adam-promo-resume-1_01": HTMLCntFlexyViewAdamPromoResume1_01Element;
        "cnt-flexy-view-adam-promo-resume-wrap": HTMLCntFlexyViewAdamPromoResumeWrapElement;
        "cnt-flexy-view-adam-promo-resume-wrapper-1_01": HTMLCntFlexyViewAdamPromoResumeWrapper1_01Element;
        "cnt-flexy-view-adam-promo-skills-1_01": HTMLCntFlexyViewAdamPromoSkills1_01Element;
        "cnt-flexy-view-adam-promo-skills-block": HTMLCntFlexyViewAdamPromoSkillsBlockElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface CntFlexyViewAdamPromoEducation1_01 {
        /**
          * Данные для блока "образование"
         */
        "payload"?: PromoResumeInterface;
    }
    interface CntFlexyViewAdamPromoEducationBlock {
        /**
          * Данные для блока "образование"
         */
        "payload"?: any;
    }
    interface CntFlexyViewAdamPromoEmployment1_01 {
        /**
          * Данные для блока "Опыт работы"
         */
        "payload"?: PromoResumeInterface;
    }
    interface CntFlexyViewAdamPromoEmploymentBlock {
        /**
          * Данные для блока "Опыт работы"
         */
        "payload"?: any;
    }
    interface CntFlexyViewAdamPromoFooter {
        /**
          * Данные для футера
         */
        "categories"?: PromoFooterBlockInterface;
    }
    interface CntFlexyViewAdamPromoFooterWrapper1_01 {
        /**
          * Данные для футера
         */
        "categories"?: PromoFooterBlockInterface;
    }
    interface CntFlexyViewAdamPromoHeader {
        /**
          * Элементы меню
         */
        "categories"?: PromoMenuItemsInterface[];
    }
    interface CntFlexyViewAdamPromoHeaderMenu {
        /**
          * Ссылки меню
         */
        "menuItems"?: PromoMenuItemsInterface;
    }
    interface CntFlexyViewAdamPromoHeaderWrapper1_01 {
        /**
          * Элементы меню
         */
        "categories"?: PromoMenuItemsInterface[];
    }
    interface CntFlexyViewAdamPromoHello {
        /**
          * Описание блока Hello
         */
        "payload"?: string;
    }
    interface CntFlexyViewAdamPromoHelloWrapper1_01 {
        /**
          * Описание блока Hello
         */
        "payload"?: string;
    }
    interface CntFlexyViewAdamPromoIntro {
        /**
          * Данные для блока интро
         */
        "payload"?: PromoIntroBlockInterface;
    }
    interface CntFlexyViewAdamPromoIntroWrapper1_01 {
        /**
          * Данные для блока интро
         */
        "payload"?: PromoIntroBlockInterface;
    }
    interface CntFlexyViewAdamPromoMobileMenu {
        /**
          * Ссылки меню
         */
        "menuItems"?: PromoMenuItemsInterface;
        "onCloseMobileMenu"?: (event: CustomEvent<void>) => void;
    }
    interface CntFlexyViewAdamPromoPortfolio {
        /**
          * Карточки портфолио
         */
        "payload"?: PromoPortfolioInterface;
    }
    interface CntFlexyViewAdamPromoPortfolioCards {
        /**
          * Карточки портфолио
         */
        "payload"?: any;
    }
    interface CntFlexyViewAdamPromoPortfolioMenu {
        /**
          * Клик по категории евент
         */
        "onClickOnPortfoliosCategory"?: (event: CustomEvent<any>) => void;
        /**
          * Данные для категорий
         */
        "payload"?: any;
    }
    interface CntFlexyViewAdamPromoPortfolioStack {
        /**
          * Данные для компонента stack
         */
        "stackList"?: any;
    }
    interface CntFlexyViewAdamPromoPortfolioWrapper1_01 {
        /**
          * Карточки портфолио
         */
        "payload"?: PromoPortfolioInterface;
    }
    interface CntFlexyViewAdamPromoResume1_01 {
        /**
          * Текст с описанием блока
         */
        "payload"?: PromoResumeInterface;
    }
    interface CntFlexyViewAdamPromoResumeWrap {
        /**
          * Текст с описанием блока
         */
        "payload"?: any;
    }
    interface CntFlexyViewAdamPromoResumeWrapper1_01 {
        /**
          * Текст с описанием блока
         */
        "payload"?: any;
    }
    interface CntFlexyViewAdamPromoSkills1_01 {
        /**
          * Данные для блока "Мои навыки"
         */
        "payload"?: PromoResumeInterface;
    }
    interface CntFlexyViewAdamPromoSkillsBlock {
        /**
          * Данные для блока "Мои навыки"
         */
        "payload"?: any;
    }
    interface MyComponent {
    }
    interface IntrinsicElements {
        "cnt-flexy-view-adam-promo-education-1_01": CntFlexyViewAdamPromoEducation1_01;
        "cnt-flexy-view-adam-promo-education-block": CntFlexyViewAdamPromoEducationBlock;
        "cnt-flexy-view-adam-promo-employment-1_01": CntFlexyViewAdamPromoEmployment1_01;
        "cnt-flexy-view-adam-promo-employment-block": CntFlexyViewAdamPromoEmploymentBlock;
        "cnt-flexy-view-adam-promo-footer": CntFlexyViewAdamPromoFooter;
        "cnt-flexy-view-adam-promo-footer-wrapper-1_01": CntFlexyViewAdamPromoFooterWrapper1_01;
        "cnt-flexy-view-adam-promo-header": CntFlexyViewAdamPromoHeader;
        "cnt-flexy-view-adam-promo-header-menu": CntFlexyViewAdamPromoHeaderMenu;
        "cnt-flexy-view-adam-promo-header-wrapper-1_01": CntFlexyViewAdamPromoHeaderWrapper1_01;
        "cnt-flexy-view-adam-promo-hello": CntFlexyViewAdamPromoHello;
        "cnt-flexy-view-adam-promo-hello-wrapper-1_01": CntFlexyViewAdamPromoHelloWrapper1_01;
        "cnt-flexy-view-adam-promo-intro": CntFlexyViewAdamPromoIntro;
        "cnt-flexy-view-adam-promo-intro-wrapper-1_01": CntFlexyViewAdamPromoIntroWrapper1_01;
        "cnt-flexy-view-adam-promo-mobile-menu": CntFlexyViewAdamPromoMobileMenu;
        "cnt-flexy-view-adam-promo-portfolio": CntFlexyViewAdamPromoPortfolio;
        "cnt-flexy-view-adam-promo-portfolio-cards": CntFlexyViewAdamPromoPortfolioCards;
        "cnt-flexy-view-adam-promo-portfolio-menu": CntFlexyViewAdamPromoPortfolioMenu;
        "cnt-flexy-view-adam-promo-portfolio-stack": CntFlexyViewAdamPromoPortfolioStack;
        "cnt-flexy-view-adam-promo-portfolio-wrapper-1_01": CntFlexyViewAdamPromoPortfolioWrapper1_01;
        "cnt-flexy-view-adam-promo-resume-1_01": CntFlexyViewAdamPromoResume1_01;
        "cnt-flexy-view-adam-promo-resume-wrap": CntFlexyViewAdamPromoResumeWrap;
        "cnt-flexy-view-adam-promo-resume-wrapper-1_01": CntFlexyViewAdamPromoResumeWrapper1_01;
        "cnt-flexy-view-adam-promo-skills-1_01": CntFlexyViewAdamPromoSkills1_01;
        "cnt-flexy-view-adam-promo-skills-block": CntFlexyViewAdamPromoSkillsBlock;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cnt-flexy-view-adam-promo-education-1_01": LocalJSX.CntFlexyViewAdamPromoEducation1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewAdamPromoEducation1_01Element>;
            "cnt-flexy-view-adam-promo-education-block": LocalJSX.CntFlexyViewAdamPromoEducationBlock & JSXBase.HTMLAttributes<HTMLCntFlexyViewAdamPromoEducationBlockElement>;
            "cnt-flexy-view-adam-promo-employment-1_01": LocalJSX.CntFlexyViewAdamPromoEmployment1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewAdamPromoEmployment1_01Element>;
            "cnt-flexy-view-adam-promo-employment-block": LocalJSX.CntFlexyViewAdamPromoEmploymentBlock & JSXBase.HTMLAttributes<HTMLCntFlexyViewAdamPromoEmploymentBlockElement>;
            "cnt-flexy-view-adam-promo-footer": LocalJSX.CntFlexyViewAdamPromoFooter & JSXBase.HTMLAttributes<HTMLCntFlexyViewAdamPromoFooterElement>;
            "cnt-flexy-view-adam-promo-footer-wrapper-1_01": LocalJSX.CntFlexyViewAdamPromoFooterWrapper1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewAdamPromoFooterWrapper1_01Element>;
            "cnt-flexy-view-adam-promo-header": LocalJSX.CntFlexyViewAdamPromoHeader & JSXBase.HTMLAttributes<HTMLCntFlexyViewAdamPromoHeaderElement>;
            "cnt-flexy-view-adam-promo-header-menu": LocalJSX.CntFlexyViewAdamPromoHeaderMenu & JSXBase.HTMLAttributes<HTMLCntFlexyViewAdamPromoHeaderMenuElement>;
            "cnt-flexy-view-adam-promo-header-wrapper-1_01": LocalJSX.CntFlexyViewAdamPromoHeaderWrapper1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewAdamPromoHeaderWrapper1_01Element>;
            "cnt-flexy-view-adam-promo-hello": LocalJSX.CntFlexyViewAdamPromoHello & JSXBase.HTMLAttributes<HTMLCntFlexyViewAdamPromoHelloElement>;
            "cnt-flexy-view-adam-promo-hello-wrapper-1_01": LocalJSX.CntFlexyViewAdamPromoHelloWrapper1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewAdamPromoHelloWrapper1_01Element>;
            "cnt-flexy-view-adam-promo-intro": LocalJSX.CntFlexyViewAdamPromoIntro & JSXBase.HTMLAttributes<HTMLCntFlexyViewAdamPromoIntroElement>;
            "cnt-flexy-view-adam-promo-intro-wrapper-1_01": LocalJSX.CntFlexyViewAdamPromoIntroWrapper1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewAdamPromoIntroWrapper1_01Element>;
            "cnt-flexy-view-adam-promo-mobile-menu": LocalJSX.CntFlexyViewAdamPromoMobileMenu & JSXBase.HTMLAttributes<HTMLCntFlexyViewAdamPromoMobileMenuElement>;
            "cnt-flexy-view-adam-promo-portfolio": LocalJSX.CntFlexyViewAdamPromoPortfolio & JSXBase.HTMLAttributes<HTMLCntFlexyViewAdamPromoPortfolioElement>;
            "cnt-flexy-view-adam-promo-portfolio-cards": LocalJSX.CntFlexyViewAdamPromoPortfolioCards & JSXBase.HTMLAttributes<HTMLCntFlexyViewAdamPromoPortfolioCardsElement>;
            "cnt-flexy-view-adam-promo-portfolio-menu": LocalJSX.CntFlexyViewAdamPromoPortfolioMenu & JSXBase.HTMLAttributes<HTMLCntFlexyViewAdamPromoPortfolioMenuElement>;
            "cnt-flexy-view-adam-promo-portfolio-stack": LocalJSX.CntFlexyViewAdamPromoPortfolioStack & JSXBase.HTMLAttributes<HTMLCntFlexyViewAdamPromoPortfolioStackElement>;
            "cnt-flexy-view-adam-promo-portfolio-wrapper-1_01": LocalJSX.CntFlexyViewAdamPromoPortfolioWrapper1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewAdamPromoPortfolioWrapper1_01Element>;
            "cnt-flexy-view-adam-promo-resume-1_01": LocalJSX.CntFlexyViewAdamPromoResume1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewAdamPromoResume1_01Element>;
            "cnt-flexy-view-adam-promo-resume-wrap": LocalJSX.CntFlexyViewAdamPromoResumeWrap & JSXBase.HTMLAttributes<HTMLCntFlexyViewAdamPromoResumeWrapElement>;
            "cnt-flexy-view-adam-promo-resume-wrapper-1_01": LocalJSX.CntFlexyViewAdamPromoResumeWrapper1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewAdamPromoResumeWrapper1_01Element>;
            "cnt-flexy-view-adam-promo-skills-1_01": LocalJSX.CntFlexyViewAdamPromoSkills1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewAdamPromoSkills1_01Element>;
            "cnt-flexy-view-adam-promo-skills-block": LocalJSX.CntFlexyViewAdamPromoSkillsBlock & JSXBase.HTMLAttributes<HTMLCntFlexyViewAdamPromoSkillsBlockElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
